###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off

file_map = {
    
    "01_use_calculator_tool.baml": "class CalculatorArguments {\n    expression string\n}\n\nclass CalculatorUsage {\n    tool_name \"calculate\"\n    arguments CalculatorArguments\n}\n\nfunction UseCalculator(goal: string) -> CalculatorUsage {\n    client Default\n    prompt #\"\n        Use the calculator to solve: {{ goal }}\n\n        {{ ctx.output_format }}\n    \"#\n}\n\ntest usage_example {\n    functions [UseCalculator]\n    args {\n        goal \"Multiply all numbers between 10 and 15\"\n    }\n}",
    "config.baml": "generator target {\n    output_type \"python/pydantic\"\n    output_dir \"..\"\n    version \"0.84.4\"\n    default_client_mode async\n}\n\nclient<llm> Default {\n  provider openai\n  options {\n    model gpt-4.1\n  }\n}\n",
}

def get_baml_files():
    return file_map